config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :recipient_groups do
    collection { post :import }
  end

  resources :recipients
  resources :campaigns
  resources :senders
  resources :email_templates

  root 'campaigns#index'
end

app/models/recipient.rb
class Recipient < ApplicationRecord
  belongs_to :recipient_group
  validates_uniqueness_of :email_to, scope: :recipient_group_id
  validates_format_of :email_to, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
end

app/controllers/recipients_controller.rb
class RecipientsController < ApplicationController
  before_action :set_recipient, only: [:show, :edit, :update, :destroy]
  before_action :set_recipient_group

  # GET /recipients
  # GET /recipients.json
  def index
    # @recipients = Recipient.where(recipient_group_id: params[:recipient_group_id])
    @recipients = Recipient.where(recipient_group_id: @recipient_group.id)
  end

  # GET /recipients/1
  # GET /recipients/1.json
  def show
  end

  # GET /recipients/new
  def new
    @recipient = Recipient.new
  end

  # GET /recipients/1/edit
  def edit
  end

  # POST /recipients
  # POST /recipients.json
  def create
    # @recipient = Recipient.new(recipient_params.merge(recipient_group_id: params[:recipient_group_id]))
    @recipient = Recipient.new(recipient_params.merge(recipient_group_id: @recipient_group))

    respond_to do |format|
      if @recipient.save
        format.html { redirect_to recipients_path(recipient_group_id: @recipient_group), notice: 'Recipient was successfully created.' }
        format.json { render :show, status: :created, location: @recipient }
      else
        format.html { render :new }
        format.json { render json: @recipient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipients/1
  # PATCH/PUT /recipients/1.json
  def update
    respond_to do |format|
      if @recipient.update(recipient_params)
        # format.html { redirect_to @recipient, notice: 'Recipient was successfully updated.' }
        # format.html { redirect_to recipients_path(recipient_group_id: params[:recipient_group_id]), notice: 'Recipient was successfully updated.' }
        format.html { redirect_to recipients_path(recipient_group_id: @recipient_group), notice: 'Recipient was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipient }
      else
        format.html { render :edit }
        format.json { render json: @recipient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipients/1
  # DELETE /recipients/1.json
  def destroy
    p params
    @recipient.destroy
    respond_to do |format|
      # format.html { redirect_to recipients_url, notice: 'Recipient was successfully destroyed.' }
      # format.html { redirect_to recipients_path(recipient_group_id: params[:recipient_group_id]), notice: 'Recipient was successfully destroyed.' }
      format.html { redirect_to recipients_path(recipient_group_id: @recipient_group), notice: 'Recipient was successfully destroyed.' }

      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipient
      @recipient = Recipient.find(params[:id])
    end

    def set_recipient_group
      @recipient_group = RecipientGroup.find(params[:recipient_group_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipient_params
      params.fetch(:recipient, {}).permit(:full_name, :designation, :department, :email_to)
    end
end

app/helpers/recipients_helper.rb
module RecipientsHelper
end

app/views/recipients/_form.html.haml
= form_for @recipient do |f|
  - if @recipient.errors.any?
    #error_explanation
      %h2= "#{pluralize(@recipient.errors.count, "error")} prohibited this recipient from being saved:"
      %ul
        - @recipient.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :full_name
    = f.text_field :full_name, class: "form-control"

  .form-group
    = f.label :designation
    = f.text_field :designation, class: "form-control"

  .form-group
    = f.label :department

    = f.text_field :department, class: "form-control"
  .form-group
    = f.label :email_to
    = f.text_field :email_to, class: "form-control"

  .actions
    = hidden_field_tag :recipient_group_id, params[:recipient_group_id]
    = f.submit 'Save', class: "btn btn-primary"

app/views/recipients/edit.html.haml
%h1 Editing recipient

= render 'form'

= link_to 'Show', @recipient
\|
= link_to 'Back', recipients_path

app/views/recipients/index.html.haml
%h1 Listing recipients

%table.table
  %thead
    %tr
      %th Full Name
      %th Designation
      %th Department
      %th Email
      %th
  %tbody
    - @recipients.each do |recipient|
      %tr
        %td= recipient.full_name
        %td= recipient.designation
        %td= recipient.department
        %td= recipient.email_to
        %td{ align: 'right' }
          = link_to 'Show', recipient_path(recipient,
            recipient_group_id: params[:recipient_group_id]),
            class: "btn btn-sm btn-primary"
          = link_to 'Edit', edit_recipient_path(recipient,
            recipient_group_id: params[:recipient_group_id]),
            class: "btn btn-sm btn-primary"
          = link_to 'Destroy', recipient_path(recipient,
            recipient_group_id: params[:recipient_group_id]),
            :method => :delete, :data => { :confirm => 'Are you sure?' },
            class: "btn btn-sm btn-primary"

%br

= link_to 'New Recipient', new_recipient_path(recipient_group_id: params[:recipient_group_id]), class: "btn btn-primary"

app/views/recipients/new.html.haml
%h1 New recipient

= render 'form'

= link_to 'Back', recipients_path

app/views/recipients/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_recipient_path(@recipient)
\|
= link_to 'Back', recipients_path