config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :recipient_groups do
    collection { post :import }
  end

  resources :recipients
  resources :campaigns
  resources :senders
  resources :email_templates

  root 'campaigns#index'
end

app/models/email_template.rb
class EmailTemplate < ApplicationRecord
  has_many :senders
end

app/controllers/email_templates_controller.rb
class EmailTemplatesController < ApplicationController
  before_action :set_email_template, only: [:show, :edit, :update, :destroy]

  # GET /email_templates
  # GET /email_templates.json
  def index
    @email_templates = EmailTemplate.all
  end

  # GET /email_templates/1
  # GET /email_templates/1.json
  def show
  end

  # GET /email_templates/new
  def new
    @email_template = EmailTemplate.new
  end

  # GET /email_templates/1/edit
  def edit
  end

  # POST /email_templates
  # POST /email_templates.json
  def create
    @email_template = EmailTemplate.new(email_template_params)

    respond_to do |format|
      if @email_template.save
        format.html { redirect_to @email_template, notice: 'Email template was successfully created.' }
        format.json { render :show, status: :created, location: @email_template }
      else
        format.html { render :new }
        format.json { render json: @email_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /email_templates/1
  # PATCH/PUT /email_templates/1.json
  def update
    respond_to do |format|
      if @email_template.update(email_template_params)
        format.html { redirect_to @email_template, notice: 'Email template was successfully updated.' }
        format.json { render :show, status: :ok, location: @email_template }
      else
        format.html { render :edit }
        format.json { render json: @email_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /email_templates/1
  # DELETE /email_templates/1.json
  def destroy
    @email_template.destroy
    respond_to do |format|
      format.html { redirect_to email_templates_url, notice: 'Email template was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_email_template
      @email_template = EmailTemplate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def email_template_params
      params.fetch(:email_template, {}).permit(:title, :description, :content, :shared)
    end
end

app/helpers/email_templates_helper.rb
module EmailTemplatesHelper
end

app/views/email_templates/_form.html.haml
= form_for @email_template do |f|
  - if @email_template.errors.any?
    #error_explanation
      %h2= "#{pluralize(@email_template.errors.count, "error")} prohibited this email_template from being saved:"
      %ul
        - @email_template.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :title
    = f.text_field :title, class: "form-control"

  .form-group
    = f.label :description
    = f.text_field :description, class: "form-control"

  .form-group
    = f.label :content
    = f.text_field :content, class: "form-control"

  .form-group
    = f.label :shared
    = f.check_box :shared
    
  .form-group
    = f.submit 'Save', class: "btn btn-primary"

app/views/email_templates/edit.html.haml
%h1 Editing email_template

= render 'form'

= link_to 'Show', @email_template
\|
= link_to 'Back', email_templates_path

app/views/email_templates/index.html.haml
.panel.panel-info
  .panel-heading
    %h4 Listing Email Templates
  .panel-body
    %table.table
      %thead
        %tr.danger
          %th Template Title
          %th Description
          %th Private
          %th

      %tbody
        - @email_templates.each do |email_template|
          %tr
            %td= email_template.title
            %td= email_template.description
            %td= email_template.shared
            %td{ align: 'right' }
              = link_to 'Show', email_template
              = link_to 'Edit', edit_email_template_path(email_template)
              = link_to 'Destroy', email_template, :method => :delete, :data => { :confirm => 'Are you sure?' }

    %br

    = link_to 'New Email template', new_email_template_path, class: "btn btn-primary"

app/views/email_templates/new.html.haml
.panel.panel-info
  .panel-heading
    %h4 New email_template
  .panel-body

    = render 'form'

-# = link_to 'Back', email_templates_path

app/views/email_templates/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_email_template_path(@email_template)
\|
= link_to 'Back', email_templates_path